const actionTypes = {
  
  //PRODUCTS
  GET_PRODUCTS_SUCCESS : 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE : 'GET_PRODUCTS_FAILURE',
  GET_PRODUCT_SUCCESS  : 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE  : 'GET_PRODUCT_FAILURE',
  GET_PRODUCT_REVIEWS_SUCCESS : 'GET_PRODUCT_REVIEWS_SUCCESS',
  GET_PRODUCT_REVIEWS_FAILURE : 'GET_PRODUCT_REVIEWS_FAILURE',

  //USER
  SIGNING_IN_SUCCESS : 'SIGNING_IN_SUCCESS',
  SIGNING_IN_FAILURE : 'SIGNING_IN_FAILURE',
  REGISTER_SUCCESS  : 'REGISTER_SUCCESS',
  REGISTER_FAILURE  : 'REGISTER_SUCCESS',
  LOGOUT_USER : 'LOGOUT_USER',
  GENERATE_UNIQUE_ID : 'GENERATE_UNIQUE_ID',

  //CART
  ADD_TO_CART_SUCCESS : 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE : 'ADD_TO_CART_FAILURE',
}

export default actionTypes;
