const actionTypes = {
  
  //PRODUCTS
  GET_PRODUCTS_SUCCESS : 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE : 'GET_PRODUCTS_FAILURE',
  GET_PRODUCT_SUCCESS  : 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE  : 'GET_PRODUCT_FAILURE',
  GET_PRODUCT_REVIEWS_SUCCESS : 'GET_PRODUCT_REVIEWS_SUCCESS',
  GET_PRODUCT_REVIEWS_FAILURE : 'GET_PRODUCT_REVIEWS_FAILURE'
}

export default actionTypes;
